### ISSUE TITLE
Dataset item type

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata-transforms#10]
Review items labeled dataset for potential conversion to another type

**Comment by sfarnel** [comment]
For review by Amanda.

On Mon, Jun 29, 2015 at 2:57 PM, Mariana Paredes-Olea <
notifications@github.com> wrote:

> Review items labeled dataset for potential conversion to another type
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/metadata-transforms/issues/10>.
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by anayram** [comment]
Amanda reviewed changed item type on several objects and remaining items will be migrated as item type Dataset.
