### ISSUE TITLE
License metadata transform specifications

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata-transforms#2]
@sfarnel, could you please check this?

A few questions came up when going through the ERA-HydraNorth stylesheet to-do list, including the [ERA metadata migration stylesheet](https://docs.google.com/spreadsheets/d/1twJvO-oEPvaSYL8HSqEf892t6-a8wUEclGN6CgKgdsI/edit#gid=0). According to specifications
>any license or rights need to be added to dcterms:rights so that it exists in descriptive metadata.

I think this sentence can be expanded a little bit as:
>copy any license information either from the `LICENSE` datastream or from `dcterms:rights` into `dcterms:rights` or `dcterms:license` as appropriate so that it exists in descriptive metadata.

In other words, get plain text rights information from either datastream and capture it in `dcterms:rights` OR get links from either datastream and capture it in `dcterms:license`.

If this is correct, one example are CreativeCommons licenses which will be captured in a dcterms:license field. With this in mind, what should take priority? copying existing CC license links from LICENSE datastream into dcterms:license or already existing in DC or DCQ rights?

Part of #11

**Comment by sfarnel** [comment]
In cases where there is a DC or DCQ rights element in addition to the license datastream, we should compare to ensure that the content is (semantically) the same. In those cases, then it shouldn't matter where the content is migrated from as long as CC licenses get into dcterms:license and anything else gets into dcterms:rights. If there are cases where there is a conflict between what is in the license datastream and what is in a DC or DCQ rights element (there shouldn't be any of these?) we should review and fix prior to transformation.
