### ISSUE TITLE
ERA internal license links

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata-transforms#3]
How should we handle internal links to license files in current ERA?

The migration script will copy internal license ERA links from the LICENSE datastream and update them to the new link in HydraNorth. This will be then captured into both HydraNorth's license field and into dcterms:license.

This means that our metadata transformation stylesheet does not need to capture those links in DCQ (therefore some objects will be migrated into HydraNorth without rights or license information in DCQ). This is just fine as I see it but I would like to confirm with @sfarnel

**Comment by sfarnel** [comment]
As long as anything internal that is a CC license gets migrated as dcterms:license and anything else gets migrated as dcterms:rights, then we should be set.
