### ISSUE TITLE
Fall launch

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata-transforms#36]
Transform and submit for migration all ERA communities, collections and items for fall launch.

ualbertalib/HydraNorth#521

**Comment by anayram** [comment]
Done. All files for ERA migration are available from:
Digital_Init shared drive
Hydra_DAMS\ERA\ERA_migration\FOXML_transformed\complete_remigration\era_final_migration
+++
Total ERA files: ~42498

Excluded from October 1st migration:
35 system files (service definitions, deployments, models, etc.)
16525 legacy theses (will be migrated later)
1101 inactive theses (2009-present)
189 deleted files
32 malformed XML files (to be migrated later)

Total files to be migrated for launch: ~24755

Files to be migrated on or after Oct 6:
16525 legacy theses
32 malformed xml files
any files updated in ERA after September 10.
