### ISSUE TITLE
Item Type - Alberta Centre for Active Living

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata-transforms#39]
Alberta Centre for Active Living
Should we change the research materials items to reports or journal article (published)?

@johnhuck 
@sfarnel

**Comment by sfarnel** [comment]
transform as is for now. will adjust items in existing ERA interface
accordingly.

On Mon, Jul 20, 2015 at 8:56 AM, Mariana Paredes-Olea <
notifications@github.com> wrote:

> Alberta Centre for Active Living
> Should we change the research materials items to reports or journal
> article (published)?
>
> @johnhuck <https://github.com/johnhuck>
> @sfarnel <https://github.com/sfarnel>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/metadata-transforms/issues/39>.
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685
