### ISSUE TITLE
ETDs with missing role (supervisor, committee member) data in FOXML

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata-transforms#40]
ETDs submitted via the ERA form should have the supervisor and committee member names, departments and roles reflected in the FOXML. We have found 25 items that do not have this.

- Sharon will review and discuss with Amanda.

**Comment by anayram** [comment]
Part of #20 and #35

**Comment by anayram** [comment]
Needs to be completed before #20 and #35

**Comment by sfarnel** [comment]
Details sent to Amanda for review; decision pending

**Comment by sfarnel** [comment]
As per meeting with Amanda and Sonya, will add metadata consistent with the content within the approved thesis (e.g., supervisor, etc.)

**Comment by sfarnel** [comment]
@anayram All items reviewed and awaiting action as described in Google doc

**Comment by sfarnel** [comment]
For the very few items where neither the thesis nor previous versions of the datastream allow confirmation of contributor role, these will be given simple property dcterms:contributor rather than anything more specific. Details in data dictionary.
