### ISSUE TITLE
thesis:degree

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata-transforms#42]
From ERA metadata migration specs"

> small number of erroneous records; fix then delete (manual work)

I will include a template in the stylesheet to get rid of this element whenever present unless there is something else to consider.

Has this manual work been completed? @sfarnel 

Part of #20

**Comment by pbinkley** [comment]
As I understand it some of the manual work is blocked by access problems
(damaged xml that Fedora can't serve) which we'll discuss at the meeting at
2:30 tomorrow.

**Comment by anayram** [comment]
Discussed issue in meeting and some items to be addressed via batch change or API - re: double-nested DCQ (ualbertalib/Hydranorth#506), missing dcterms datastream (ualbertalib/Hydranorth#287)

thesis:degree issue changed manually.
