### ISSUE TITLE
Inactive legacy theses

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata-transforms#48]
~ 4170 legacy theses are currently 'inactive' in ERA. From a sampling, the DS is an external resource which sits on a filepath on Chelsea. Examples:

https://era.library.ualberta.ca/public/view/item/uuid:73beac61-007a-42b0-8ebf-ad2a6cd99cf1/
https://era.library.ualberta.ca/public/view/item/uuid:f31cd505-40ba-4788-9063-10f5c56259a4/
https://era.library.ualberta.ca/public/view/item/uuid:f506ab2a-4216-45c9-bb4d-8d2f9c96f786/
https://era.library.ualberta.ca/public/view/item/uuid:5cfbde89-c410-4af4-99d5-e310a89e3673/
https://era.library.ualberta.ca/public/view/item/uuid:ac3aba6b-ef56-4e98-9908-c2872731ab40/
https://era.library.ualberta.ca/public/view/item/uuid:282015d6-76ad-4004-a14e-3df67eff070b/
https://era.library.ualberta.ca/public/view/item/uuid:c75751e1-48b0-43ba-89ba-5ac702d50571/
https://era.library.ualberta.ca/public/view/item/uuid:414a6eec-4683-4cd9-a51e-e17ca76b8a45/
https://era.library.ualberta.ca/public/view/item/uuid:9bfb236d-e2ab-4881-8f99-9628e60b4d56/
https://era.library.ualberta.ca/public/view/item/uuid:7b7e6478-6740-486d-b726-44c8c5e6c28b/

Thoughts @weiweishi or @criedlberger ?

**Comment by pbinkley** [comment]
We decided to solve the problem of the hardcoded chelsea external resources by applying chelsea's domain name to the new era server (in its hosts file). It therefore should be possible to download the external datastreams for these items, but I've tried one and it says datastream not found. I can't investigate any further from home, and I'm not sure where we left this. It should be the case that an external datastream url like http://chelsea.library.ualberta.ca/external/proquest_theses/MK/17/73/6/MK17736.pdf gets served from a local directory on the new era server. Henry will have be involved in looking into this.

**Comment by sfarnel** [comment]
Thanks Peter.

On Sun, Aug 9, 2015 at 10:23 AM, Peter Binkley <notifications@github.com>
wrote:

> We decided to solve the problem of the hardcoded chelsea external
> resources by applying chelsea's domain name to the new era server (in its
> hosts file). It therefore should be possible to download the external
> datastreams for these items, but I've tried one and it says datastream not
> found. I can't investigate any further from home, and I'm not sure where we
> left this. It should be the case that an external datastream url like
> http://chelsea.library.ualberta.ca/external/proquest_theses/MK/17/73/6/MK17736.pdf
> gets served from a local directory on the new era server. Henry will have
> be involved in looking into this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/metadata-transforms/issues/48#issuecomment-129212762>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by anayram** [comment]
All those inactive theses have a unicorn ID in the FOXML. I spotted checked some of them in the library catalogue and they are active.

**Comment by sfarnel** [comment]
these were determined to be items that did not have associated pdfs and so became inactive. will be addressed post-launch with ingest of large group of legacy theses that have never lived in ERA.
