### ISSUE TITLE
Checking ERA items without community association

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata-transforms#6]
[266 ERA objects with no community association](https://docs.google.com/spreadsheets/d/11Cla_v3gxVp3Me3A2Ta6G-vbU2m6t_Nesed9a3_gP20/edit#gid=0): I finished going through this list and flagged the status of each item (active, inactive, deleted).

There are some active items that are test submissions that we could mark inactive, as well as some active items that may need a community association. Other cases are inactive items like theses that are pending to be approved so those will be addressed at some point, if I got it right.

**Comment by sfarnel** [comment]
Amanda and I met to review the ERA items with no community. Metadata team will review items and either a) add to appropriate community (few if any cases) or b) delete items. Will consult with Amanda as needed.

**Comment by anayram** [comment]
Sharon will look at these and then if something is outstanding we will take it to Amanda and tackle later.

**Comment by sfarnel** [comment]
active items reviewed and handled. inactive and deleted can be given final
review prior to pre-launch purge.

On Tue, Jul 21, 2015 at 10:51 AM, Mariana Paredes-Olea <
notifications@github.com> wrote:

> Sharon will look at these and then if something is outstanding we will
> take it to Amanda and tackle later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/metadata-transforms/issues/6#issuecomment-123400486>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685
